version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - /docker/frontend:/app
    stdin_open: true
    tty: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - /docker/frontend:/app
    command: ["npm", "run", "test"]
